name: Trigger PHP Script

on:
  schedule:
    - cron: '2 */5 * * * *' # Runs every 5 minutes at 2, 7, 12, etc., minutes past
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-script:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP Request to PHP Script
        id: curl
        run: |
          response=$(curl -s -w "%{http_code}" -X GET "https://synops.dev/cronjobs/fetch_api_data.php" -H "User-Agent: GitHub-Actions-Cron")
          status=${response: -3}
          echo "HTTP Status: $status"
          echo "::set-output name=status::$status"
      - name: Notify on Failure
        if: steps.curl.outputs.status != '200'
        run: |
          echo "Failed to trigger PHP script. HTTP Status: ${{ steps.curl.outputs.status }}"
          # Optional: Add Slack/email notification
